import 'dart:convert';
import 'dart:io';
import 'package:crypto/crypto.dart';
import 'package:path/path.dart' as p;
import 'config.dart';
import 'dialect.dart';

String dartString(String value) => jsonEncode(value).replaceAll(r'$', r'\$');
String valueExpression(String value) => isPlaceholder(value)
    ? 'resolveValue(${dartString(value)})'
    : dartString(value);
String compileStep(Step s) {
  String finder(String target, String value) => target == 'key'
      ? 'find.byKey(const ValueKey<String>(${dartString(value)}))'
      : 'find.text(${dartString(value)})';
  if (s.assertion) {
    final parts = s.kind.split('_');
    final f = finder(parts[1], s.args[0]);
    final count = parts[2] == 'visible'
        ? null
        : parts[2] == 'absent'
        ? '0'
        : s.args[1];
    return 'await assertVisible(\$, $f, ${count ?? 'null'});';
  }
  switch (s.kind) {
    case 'environment':
      return '// Environment enforced by bootstrap and execution preflight.';
    case 'tap_key':
      return 'await \$(${finder('key', s.args[0])}).tap();';
    case 'tap_text':
      return 'await \$(${finder('text', s.args[0])}).tap();';
    case 'enter':
      return 'await \$(${finder('key', s.args[1])}).enterText(${valueExpression(s.args[0])});';
    case 'enter_focused':
      return 'await \$.tester.enterText(gherkinFocusedField(), ${valueExpression(s.args[0])});\n    await \$.pump();';
    case 'scroll_key':
      return 'await \$(${finder('key', s.args[0])}).scrollTo();';
    case 'scroll_text':
      return 'await \$(${finder('text', s.args[0])}).scrollTo();';
    case 'wait':
      return 'await \$.pump(const Duration(milliseconds: ${s.args[0]}));';
    case 'home':
      return r'await $.platform.mobile.pressHome();';
    case 'notifications':
      return r'await $.platform.mobile.openNotifications();';
    case 'grant':
      return r'if (await $.platform.mobile.isPermissionDialogVisible()) { await $.platform.mobile.grantPermissionWhenInUse(); }';
    case 'deny':
      return r'if (await $.platform.mobile.isPermissionDialogVisible()) { await $.platform.mobile.denyPermission(); }';
    case 'notification':
      return 'await \$.platform.mobile.tapOnNotificationBySelector(Selector(text: ${dartString(s.args[0])}));';
    default:
      throw GherkinException('Cannot compile ${s.kind}');
  }
}

String generatePatrol(Feature feature, ProjectConfig config, String output) {
  validateSupport(feature, Backend.patrol, expand: config.expand);
  final import = p
      .relative(inside(config.root, config.bootstrap), from: p.dirname(output))
      .replaceAll('\\', '/');
  final source = p
      .relative(feature.path, from: config.root)
      .replaceAll('\\', '/');
  final sourceFile = File(feature.path);
  final digest = sha256
      .convert(
        utf8.encode(
          '${sourceFile.existsSync() ? sourceFile.readAsStringSync() : feature.name}\n${jsonEncode(config.data)}',
        ),
      )
      .toString();
  final expandedSteps = feature.allSteps.expand(config.expand).toList();
  final usesFocused = expandedSteps.any((s) => s.kind == 'enter_focused');
  final usesKey = expandedSteps.any(
    (s) => s.kind.contains('_key') || s.kind == 'enter',
  );
  final usesFinder = expandedSteps.any(
    (s) =>
        s.assertion ||
        s.kind.startsWith('tap_') ||
        s.kind.startsWith('scroll_') ||
        s.kind == 'enter',
  );
  final out = StringBuffer(
    '''// GENERATED by gherkin. Edit the source feature, never this file.
// Source: ${jsonEncode(source)}
// Inputs SHA256: $digest
${usesKey || usesFocused ? "import 'package:flutter/widgets.dart';" : ''}
${usesFinder || usesFocused ? "import 'package:flutter_test/flutter_test.dart';" : ''}
import 'package:patrol/patrol.dart';
import ${dartString(import)};

void main() {
''',
  );
  for (final scenario in feature.scenarios) {
    final steps = [
      ...feature.background,
      ...scenario.steps,
    ].expand(config.expand).toList();
    out.writeln(
      '  patrolTest(${dartString('${feature.name}: ${scenario.name}')}, (\$) async {',
    );
    out.writeln(
      '    await startApp(\$, environment: ${dartString(config.environment)}, production: ${config.data['production']});',
    );
    for (final s in steps) {
      out.writeln('    ${compileStep(s)}');
    }
    out.writeln('  }, tags: ${jsonEncode(scenario.tags)});');
  }
  out.writeln('}');
  if (usesFocused) out.writeln(focusedFieldHelper);
  return out.toString();
}

// Generated locally so existing, app-owned bootstraps need no migration.
const focusedFieldHelper = '''
Finder gherkinFocusedField() {
  final finder = find.byWidgetPredicate(
    (widget) => widget is EditableText && widget.focusNode.hasPrimaryFocus,
    description: 'EditableText owning primary focus',
  );
  final count = finder.evaluate().length;
  if (count != 1) {
    throw TestFailure('Expected one focused editable field; found \$count');
  }
  return finder;
}
''';

Future<String> formatGenerated(
  ProjectConfig c,
  String output,
  String source,
) async {
  final command = c.dart;
  final process = await Process.start(command.first, [
    ...command.skip(1),
    'format',
    '--output=show',
    '--summary=none',
    '--stdin-name',
    output,
  ], workingDirectory: c.appRoot);
  final formatted = process.stdout.transform(utf8.decoder).join();
  final errors = process.stderr.drain<void>();
  process.stdin.write(source);
  await process.stdin.close();
  final status = await process.exitCode;
  await errors;
  final result = await formatted;
  if (status != 0) throw GherkinException('Dart formatting failed');
  return result;
}

Future<List<String>> generateSuite(
  ProjectConfig c,
  List<File> files, {
  bool check = false,
}) async {
  final pending = <String, String>{};
  for (final f in files) {
    final feature = parseFeature(f.readAsStringSync(), path: f.path);
    final relative = p.relative(
      f.path,
      from: p.join(c.root, 'gherkin/features'),
    );
    final output = inside(
      c.appRoot,
      p.join('integration_test', '${p.withoutExtension(relative)}_test.dart'),
    );
    final existing = File(output);
    if (existing.existsSync() &&
        !existing.readAsStringSync().startsWith('// GENERATED by gherkin.')) {
      throw GherkinException(
        'Refusing to overwrite hand-written test: ${p.relative(output, from: c.root)}',
      );
    }
    pending[output] = generatePatrol(feature, c, output);
  }
  // Stage and format the entire batch before touching committed output.
  final staged = <String, String>{};
  for (final entry in pending.entries) {
    staged[entry.key] = await formatGenerated(c, entry.key, entry.value);
  }
  if (check) {
    final stale = staged.entries
        .where(
          (e) =>
              !File(e.key).existsSync() ||
              File(e.key).readAsStringSync() != e.value,
        )
        .map((e) => p.relative(e.key, from: c.root))
        .toList();
    final expected = pending.keys.toSet();
    final allFeatures = resolveFeatures(c, 'gherkin');
    if (files.length == allFeatures.length) {
      final generatedDir = Directory(c.patrolTestDirectory);
      if (generatedDir.existsSync()) {
        for (final file
            in generatedDir
                .listSync(recursive: true, followLinks: false)
                .whereType<File>()) {
          if (file.path.endsWith('_test.dart') &&
              !expected.contains(file.path) &&
              file.readAsStringSync().startsWith('// GENERATED by gherkin.')) {
            stale.add(p.relative(file.path, from: c.root));
          }
        }
      }
    }
    if (stale.isNotEmpty) {
      throw GherkinException('Stale generated output: ${stale.join(', ')}');
    }
  } else {
    for (final entry in staged.entries) {
      File(entry.key).parent.createSync(recursive: true);
      File(entry.key).writeAsStringSync(entry.value);
    }
  }
  return pending.keys.toList();
}
