// GENERATED by gherkin. Edit the source feature, never this file.
// Source: "gherkin/features/focused.feature"
// Inputs SHA256: 0cf0b1183fa6e06095f7a6289771c6051c72ed67606e56a4b160350168db7712
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:patrol/patrol.dart';
import "../gherkin/support/patrol_bootstrap.dart";

void main() {
  patrolTest("Focused search: Search without a field key", ($) async {
    await startApp($, environment: "local", production: false);
    // Environment enforced by bootstrap and execution preflight.
    await $(find.byKey(const ValueKey<String>("open_search"))).tap();
    await $.tester.enterText(gherkinFocusedField(), "movie");
    await $.pump();
    await assertVisible($, find.text("Query: movie"), null);
    await $.tester.enterText(gherkinFocusedField(), "");
    await $.pump();
    await assertVisible($, find.text("Query: "), null);
  }, tags: []);
}

Finder gherkinFocusedField() {
  final finder = find.byWidgetPredicate(
    (widget) => widget is EditableText && widget.focusNode.hasPrimaryFocus,
    description: 'EditableText owning primary focus',
  );
  final count = finder.evaluate().length;
  if (count != 1) {
    throw TestFailure('Expected one focused editable field; found $count');
  }
  return finder;
}
