// GENERATED by gherkin. Edit the source feature, never this file.
// Source: "gherkin/features/login.feature"
// Inputs SHA256: 52abe5670da5e01559a5c4ec126a6a05614839fb2148d5718c3b1aab36951307
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:patrol/patrol.dart';
import "../gherkin/support/patrol_bootstrap.dart";

void main() {
  patrolTest("Fixture form: Submit a name", ($) async {
    await startApp($, environment: "local", production: false);
    // Environment enforced by bootstrap and execution preflight.
    await $(find.byKey(ValueKey<String>("name_field"))).tap();
    await $(find.byKey(ValueKey<String>("name_field"))).enterText("Ada");
    await $(find.byKey(ValueKey<String>("submit"))).tap();
    await assertVisible($, find.byKey(ValueKey<String>("result")), null);
    await assertVisible($, find.text("Complete"), 1);
    await assertVisible($, find.byKey(ValueKey<String>("missing")), 0);
  }, tags: ["smoke"]);
}
